# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"D\n\x06\x45vents\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x65st\x18\x04 \x01(\x05\".\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x07.Events\"\'\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x32\x33\n\x0bRPCServicer\x12$\n\x0bMsgDelivery\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTS._serialized_start=17
  _EVENTS._serialized_end=85
  _REQUEST._serialized_start=87
  _REQUEST._serialized_end=133
  _RESPONSE._serialized_start=135
  _RESPONSE._serialized_end=174
  _RPCSERVICER._serialized_start=176
  _RPCSERVICER._serialized_end=227
# @@protoc_insertion_point(module_scope)
